version: '3'

services:
  client:
    build:
      context: ./client/
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - 35792:35792
      - 9009:9009
    environment:
      - NODE_ENV=dev
      - NODE_PATH=/usr/app/node_modules
      - CHOKIDAR_USEPOLLING=true
    entrypoint: /bin/bash run.sh
    command: storybook

  server:
    build:
      context: ./server/
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
      - /usr/app
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=dev
      - NODE_PATH=/usr/app/node_modules
      - CHOKIDAR_USEPOLLING=true
    command: tail -f /dev/null


