version: '3'

services:
  client:
    build:
      context: ./client/
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - 35792:35792
      - 9009:9009
      - 3000:3000
    environment:
      - NODE_ENV=dev
      - NODE_PATH=/usr/app/node_modules
      - SERVER_URL=server:8000
      - CHOKIDAR_USEPOLLING=true
    entrypoint: /bin/bash run.sh
    command: start
    links:
      - server

  dbmongo:
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 29213:29213
    command: mongod --port 29213 --smallfiles --logpath=/dev/null # --quiet


  server:
    build:
      context: ./server/
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
      - /usr/app
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=dev
      - NODE_PATH=/usr/app/node_modules
      - MONGODB_URI=mongodb://dbmongo:29213
      - MONGODB_NS=docker-todos-test
      - CHOKIDAR_USEPOLLING=true
    command: nodemon -L index.js
    links:
      - dbmongo


